import { createServerFn } from "@tanstack/react-start";

export type PhotoAnalysis = {
  category:
    | "Fire" | "Smoke" | "Dumping" | "Air Pollution" | "Water Pollution"
    | "Trash" | "Graffiti" | "Pothole" | "Streetlight" | "Sidewalk" | "Tree" | "Signage" | "Other";
  severity: "none" | "low" | "medium" | "high" | "critical";
  confidence: number;
  title: string;
  description: string;
  reasoning: string;
  isGenuine: boolean;
  genuineReason: string;
  descriptionMatch: boolean;
  descriptionMatchReason: string;
};

const TITLE_MAP: Record<string, string> = {
  Fire: "Active fire hazard detected",
  Smoke: "Smoke plume visible in area",
  Dumping: "Illegal dumping site reported",
  "Air Pollution": "Air quality concern visible",
  "Water Pollution": "Water contamination detected",
  Trash: "Trash / litter on site",
  Graffiti: "Graffiti on property",
  Pothole: "Road damage / pothole reported",
  Streetlight: "Streetlight issue reported",
  Sidewalk: "Sidewalk damage detected",
  Tree: "Tree / vegetation issue",
  Signage: "Signage problem reported",
  Other: "Issue report submitted",
};

function buildAnalysis(
  category: string,
  severity: string,
  confidence: number,
  isGenuine: boolean,
  genuineReason: string,
  description: string,
  reasoning: string,
): PhotoAnalysis {
  return {
    category: category as PhotoAnalysis["category"],
    severity: severity as PhotoAnalysis["severity"],
    confidence,
    title: TITLE_MAP[category] ?? "Issue report submitted",
    description: description || "Photo analyzed and issue classified.",
    reasoning,
    isGenuine,
    genuineReason,
    descriptionMatch: true,
    descriptionMatchReason: description
      ? `Description provided by user: "${description.substring(0, 100)}${description.length > 100 ? "..." : ""}"`
      : "No user description provided to cross-check.",
  };
}

function checkGenuine(tags: string[], desc: string): { isGenuine: boolean; reason: string } {
  const combined = (tags.join(" ") + " " + desc).toLowerCase();
  const stockPatterns = ["stock photo", "shutterstock", "istock", "getty", "depositphotos", "dreamstime"];
  const aiPatterns = ["ai generated", "stable diffusion", "midjourney", "dalle-", "generated by"];
  for (const p of stockPatterns) if (combined.includes(p)) return { isGenuine: false, reason: "Likely a stock photo — not an original on-site capture." };
  for (const p of aiPatterns) if (combined.includes(p)) return { isGenuine: false, reason: "Possible AI-generated image detected." };
  return { isGenuine: true, reason: "Photo appears to be a genuine on-site capture." };
}

export const analyzePhoto = createServerFn({ method: "POST" })
  .inputValidator((data: { imageDataUrl: string; description?: string }) => {
    if (!data?.imageDataUrl?.startsWith("data:image/")) {
      throw new Error("imageDataUrl must be a data:image/* URL");
    }
    return data;
  })
  .handler(async ({ data }): Promise<PhotoAnalysis> => {
    const mimeType = data.imageDataUrl.split(";")[0].split(":")[1];
    const base64Data = data.imageDataUrl.split(",")[1];

    // Try Groq (free tier — llama-3.2-11b-vision-preview, no credit card)
    const groqKey = process.env.GROQ_API_KEY;
    console.log("[analyzePhoto] GROQ_API_KEY present:", !!groqKey, "Key preview:", groqKey?.substring(0, 20));
    if (groqKey) {
      try {
        const resp = await fetch("https://api.groq.com/openai/v1/chat/completions", {
          method: "POST",
          headers: {
            Authorization: `Bearer ${groqKey}`,
            "Content-Type": "application/json",
          },
          body: JSON.stringify({
            model: "meta-llama/llama-4-scout-17b-16e-instruct",
            messages: [
              {
                role: "user",
                content: [
                  {
                    type: "text",
                    text: `You are CivicFix Vision — a civic issue analyzer. Analyze this photo and respond with ONLY a valid JSON object (no markdown, no explanation):
{
  "category": "Fire|Smoke|Dumping|Air Pollution|Water Pollution|Trash|Graffiti|Pothole|Streetlight|Sidewalk|Tree|Signage|Other",
  "severity": "none|low|medium|high|critical",
  "confidence": 0.0-1.0,
  "isGenuine": true|false,
  "tags": ["tag1","tag2"...max 10]
}
Rules:
- isGenuine: false if it looks like a stock photo, AI-generated, or screenshot
- severity: critical for fire/flood, high for smoke/dumping, medium for pothole/damage, low for litter/minor issues
- Return valid JSON only`,
                  },
                  {
                    type: "image_url",
                    image_url: { url: `data:${mimeType};base64,${base64Data}` },
                  },
                ],
              },
            ],
            temperature: 0.2,
          }),
        });

        if (resp.ok) {
          const json = await resp.json();
          const raw = json?.choices?.[0]?.message?.content;
          if (raw) {
            const parsed = JSON.parse(raw.trim());
            const tags = parsed.tags ?? [];
            const { isGenuine, reason } = checkGenuine(tags, data.description ?? "");
            console.log("[analyzePhoto] Groq success:", parsed.category);
            return buildAnalysis(
              parsed.category ?? "Other",
              parsed.severity ?? "medium",
              parsed.confidence ?? 0.8,
              isGenuine,
              reason,
              data.description ?? "",
              `Groq AI classified as ${parsed.category} with ${parsed.severity} severity. Tags: ${tags.join(", ")}.`,
            );
          } else {
            console.log("[analyzePhoto] Groq response empty or malformed:", json);
          }
        } else {
          const errText = await resp.text();
          console.log("[analyzePhoto] Groq API error:", resp.status, resp.statusText, errText);
        }
      } catch (error) {
        console.error("[analyzePhoto] Groq fetch error:", error instanceof Error ? error.message : String(error));
        // fall through to fallback
      }
    }

    // Fallback: aiautotagging.com (free, no API key needed, 500/day)
    try {
      const blob = await fetch(data.imageDataUrl).then((r) => r.blob());
      const formData = new FormData();
      formData.append("file", blob, "photo.jpg");

      const resp = await fetch("https://aiautotagging.com/api/tag/image", {
        method: "POST",
        body: formData,
      });

      if (resp.ok) {
        const json = await resp.json();
        const tags: string[] = Array.isArray(json?.tags)
          ? json.tags
          : Array.isArray(json?.labels)
            ? json.labels
            : typeof json?.result === "string"
              ? [json.result]
              : [];

        const tagStr = tags.join(", ");
        const { isGenuine, reason } = checkGenuine(tags, data.description ?? "");

        const categoryMap: Record<string, string> = {
          fire: "Fire", flame: "Fire", burning: "Fire",
          smoke: "Smoke", smog: "Air Pollution", haze: "Air Pollution",
          waste: "Dumping", dump: "Dumping", debris: "Dumping", trash: "Trash", litter: "Trash", garbage: "Trash",
          graffiti: "Graffiti", tagging: "Graffiti",
          pothole: "Pothole", road: "Pothole", crack: "Pothole",
          streetlight: "Streetlight", light: "Streetlight",
          water: "Water Pollution", river: "Water Pollution",
          tree: "Tree", vegetation: "Tree",
          building: "Other", house: "Other", construction: "Other",
        };

        const sevMap: Record<string, string> = {
          fire: "critical", flame: "critical",
          smoke: "high", smog: "high", dump: "high", waste: "high",
          flood: "critical", accident: "high",
          pothole: "medium", crack: "medium", road: "medium",
          water: "medium", pollution: "high",
          graffiti: "low", trash: "low", litter: "low",
        };

        let topCat = "Other";
        let topSev = "low";
        let topSevScore = 0;
        for (const tag of tags) {
          const lower = tag.toLowerCase();
          if (categoryMap[lower]) topCat = categoryMap[lower]!;
          if (sevMap[lower]) {
            const score = { none: 0, low: 1, medium: 2, high: 3, critical: 4 }[sevMap[lower]] ?? 1;
            if (score > topSevScore) {
              topSev = sevMap[lower]!;
              topSevScore = score;
            }
          }
        }

        return buildAnalysis(
          topCat,
          topSev,
          0.7,
          isGenuine,
          reason,
          data.description ?? "",
          `Analyzed via aiautotagging.com. Detected tags: ${tagStr || "none"}. Category: ${topCat}, Severity: ${topSev}.`,
        );
      }
    } catch {
      // fall through
    }

    // Final local fallback
    return buildAnalysis(
      "Other", "low", 0.5, true,
      "Photo received and report submitted successfully.",
      data.description ?? "",
      "Image analysis unavailable — report submitted with default classification. Photo will be reviewed by moderators.",
    );
  });