/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReportRouteImport } from './routes/report'
import { Route as IssuesRouteImport } from './routes/issues'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IssuesIdRouteImport } from './routes/issues.$id'

const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuesRoute = IssuesRouteImport.update({
  id: '/issues',
  path: '/issues',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuesIdRoute = IssuesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => IssuesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/issues': typeof IssuesRouteWithChildren
  '/report': typeof ReportRoute
  '/issues/$id': typeof IssuesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/issues': typeof IssuesRouteWithChildren
  '/report': typeof ReportRoute
  '/issues/$id': typeof IssuesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/issues': typeof IssuesRouteWithChildren
  '/report': typeof ReportRoute
  '/issues/$id': typeof IssuesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/issues' | '/report' | '/issues/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/issues' | '/report' | '/issues/$id'
  id: '__root__' | '/' | '/about' | '/issues' | '/report' | '/issues/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  IssuesRoute: typeof IssuesRouteWithChildren
  ReportRoute: typeof ReportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issues': {
      id: '/issues'
      path: '/issues'
      fullPath: '/issues'
      preLoaderRoute: typeof IssuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issues/$id': {
      id: '/issues/$id'
      path: '/$id'
      fullPath: '/issues/$id'
      preLoaderRoute: typeof IssuesIdRouteImport
      parentRoute: typeof IssuesRoute
    }
  }
}

interface IssuesRouteChildren {
  IssuesIdRoute: typeof IssuesIdRoute
}

const IssuesRouteChildren: IssuesRouteChildren = {
  IssuesIdRoute: IssuesIdRoute,
}

const IssuesRouteWithChildren =
  IssuesRoute._addFileChildren(IssuesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  IssuesRoute: IssuesRouteWithChildren,
  ReportRoute: ReportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
